sudo: false
services:
  - docker
language: erlang
otp_release:
  - "22.2"
cache:
  directories:
    - $HOME/otp/22.2
    - $HOME/.cache/rebar3
    - _plt
install: "true"
script: "make travis"
branches:
  only:
    - master
    - develop
notifications:
  email:
    - pj+travis@ezgr.net
